* Encoding: UTF-8.

*MANOVA

DATASET ACTIVATE DataSet3.
GLM Friendly Helpfulness Negativity BY Gender1F2M Race1L2W
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /PRINT=DESCRIPTIVE ETASQ HOMOGENEITY
  /CRITERIA=ALPHA(.05)
  /DESIGN= Gender1F2M Race1L2W Gender1F2M*Race1L2W.


