---
title: "Untitled"
author: "Felix Wu"
date: "5/4/2020"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r interrater reliaility,echo=TRUE}
library(psych)
library(readxl)
library(reshape)
library(irr)
# library(psy)
library(nFactors)
# library(irr::icc)
library(psych)
library(readxl)
library(reshape)
library(irr)
# library(psy)
library(nFactors)
library(xlsx)
library(DescTools)
library(factoextra)
library(lavaan)
coding.data <-
  read_excel("C:/Felix/Felix/Toothbrush Study/Audio Coding (Responses).xlsx",
             na = c("", "n/a"))

table(coding.data$`Was this audio codable?`)


factor.data <-
  data.frame(
    coding.data$`How friendly was the receptionist AFTER the script was delivered?`,
    coding.data$`How interested did she/he seem?`,
    coding.data$`How favorable was the receptionist?`,
    coding.data$`How willing was she/he seem to help?...14`,
    coding.data$`Friendliness: How friendly was the conversation overall?`,
    coding.data$`Curtness: How curt was the conversation overall?`,
    coding.data$`Warmth: How warm was the conversation overall?`,
    coding.data$`Rude: How rude was the conversation overall?`,
    coding.data$`Empathetic: How empathetic was the conversation overall?`,
    coding.data$`Helpful: How helpful was the conversation overall?`,
    coding.data$`Overall was the interaction negative or positive?`
  )
fa.parallel(factor.data, fm = "ml")
# factor.data <- na.omit(factor.data)
# ev <- eigen(cor(factor.data))
# ap <- parallel(subject=nrow(factor.data),var=ncol(factor.data), rep=100, cent=.05)
# nS <- nScree(x=ev$values, aparallelap$eigen$qevpea)
# plotnScree(nS)
factor.data <- na.omit(factor.data)
fit <- factanal(factor.data, 3, rotation = "varimax")
print(fit,
      digits = 6,
      sort = TRUE)

#Factor 1: friendly.after.script, favoralbe, friendliness,  warmth, - rudeness, empathetic, overall interaction,
#factor 2: hinterested, willing.help, helpful
#facotr 3: - curtness, -rudeness
with.empathy <- "Friendly =~  
  coding.data..How.friendly.was.the.receptionist.AFTER.the.script.was.delivered.. + 
  coding.data..How.favorable.was.the.receptionist..+
  coding.data..Friendliness..How.friendly.was.the.conversation.overall..+
  coding.data..Warmth..How.warm.was.the.conversation.overall..+
  coding.data..Empathetic..How.empathetic.was.the.conversation.overall..+
  coding.data..Overall.was.the.interaction.negative.or.positive..
  Helpful =~ coding.data..How.interested.did.she.he.seem..+
  coding.data..How.willing.was.she.he.seem.to.help....14.+
  coding.data..Helpful..How.helpful.was.the.conversation.overall..
  Negativity =~ coding.data..Curtness..How.curt.was.the.conversation.overall..+
  coding.data..Rude..How.rude.was.the.conversation.overall.." 
cfa.with.empathy <- cfa(model=with.empathy, data=factor.data,std.lv=TRUE) 
summary(cfa.with.empathy, fit.measures=TRUE, standardized=TRUE)
semPlot::semPaths(cfa.with.empathy, "mod", whatLabels="std", nCharNodes=0, edge.label.cex=.8, mar=c(10, 10, 10, 10), fade=F)


without.empathy <- "Friendly =~  
  coding.data..How.friendly.was.the.receptionist.AFTER.the.script.was.delivered.. + 
  coding.data..How.favorable.was.the.receptionist..+
  coding.data..Friendliness..How.friendly.was.the.conversation.overall..+
  coding.data..Warmth..How.warm.was.the.conversation.overall..+
  coding.data..Overall.was.the.interaction.negative.or.positive..
  Helpful =~ coding.data..How.interested.did.she.he.seem..+
  coding.data..How.willing.was.she.he.seem.to.help....14.+
  coding.data..Helpful..How.helpful.was.the.conversation.overall..
  Negativity =~ coding.data..Curtness..How.curt.was.the.conversation.overall..+
  coding.data..Rude..How.rude.was.the.conversation.overall.." 
cfa.without.empathy <- cfa(model=without.empathy, data=factor.data,std.lv=TRUE) 
summary(cfa.without.empathy, fit.measures=TRUE, standardized=TRUE)
semPlot::semPaths(cfa.without.empathy, "mod", whatLabels="std", nCharNodes=0, edge.label.cex=.8, mar=c(10, 10, 10, 10), fade=F)

anova(cfa.without.empathy, cfa.with.empathy)

scaled_df <- apply(factor.data, 2, scale)
comp.cov <- cov(scaled_df)
comp.eigen <- eigen(comp.cov)
str(comp.eigen)
phi <- comp.eigen$vectors[,1]
phi <- -phi
# row.names(phi) <- c("Murder", "Assault", "UrbanPop", "Rape")
# colnames(phi) <- c("PC1")
phi
PC1 <- as.matrix(scaled_df) %*% phi
PC <- data.frame(observations = row.names(factor.data), PC1)
coding.data <- data.frame(coding.data, observations = row.names(coding.data))
coding.data <- merge(coding.data, PC, by.x="observations" )

video.Positivity <-
  data.frame(
    coding.data$Coder.Name..3.letter.initials.,
    coding.data$Dentist.Sample.ID..ex..102.1.,
    coding.data$PC1
  )
names(video.Positivity) <- c("NetId", "Trial" , "Positivity")
md.Positivity <-
  melt(video.Positivity, id.vars = cbind("Trial", "NetId"))

cast.Positivity <- cast(md.Positivity, Trial ~ variable + NetId, sum)
cast.Positivity <- data.frame(cast.Positivity)
cast.Positivity <- na.omit(cast.Positivity)
rownames(cast.Positivity) <- cast.Positivity$Trial
# all.codings.factor <- cast.Positivity
cast.Positivity$Trial <- as.factor(cast.Positivity$Trial)
cast.Positivity$Trial <- NULL
str(cast.Positivity)
DescTools::ICC(cast.Positivity)
#Factor 1: friendly.after.script, favoralbe, friendliness,  warmth, - rudeness, empathetic, overall interaction,
#factor 2: hinterested, willing.help, helpful
#facotr 3: - curtness, -rudeness

# coding.data$Curtness.R <-
#   dplyr::recode(
#     coding.data$`Curtness: How curt was the conversation overall?`,
#     "7" = 1,
#     "6" = 2,
#     "5" = 3,
#     "4" = 4,
#     "3" = 5,
#     "2" = 6,
#     "1" = 7
#   )
# 
# coding.data$Rudeness.R <-
#   dplyr::recode(
#     coding.data$`Rude: How rude was the conversation overall?`,
#     "7" = 1,
#     "6" = 2,
#     "5" = 3,
#     "4" = 4,
#     "3" = 5,
#     "2" = 6,
#     "1" = 7
#   )

#removed empathy because of higher levels of cross loadings
coding.data$Friendly <-
  (
    coding.data$Friendliness..How.friendly.was.the.conversation.overall. +
    coding.data$How.favorable.was.the.receptionist. +
    coding.data$How.friendly.was.the.receptionist.AFTER.the.script.was.delivered. +
    coding.data$Warmth..How.warm.was.the.conversation.overall. +
    coding.data$Overall.was.the.interaction.negative.or.positive.#+
    #coding.data$Empathetic..How.empathetic.was.the.conversation.overall.
  ) / 5


coding.data$Negativity <-
  (
    coding.data$Curtness..How.curt.was.the.conversation.overall. + 
    coding.data$Rude..How.rude.was.the.conversation.overall.
  ) / 2

coding.data$Helpfulness <-
  (
    coding.data$How.interested.did.she.he.seem. + 
    coding.data$How.willing.was.she.he.seem.to.help....14 + 
    coding.data$Helpful..How.helpful.was.the.conversation.overall.
  ) / 3
#
#
# coding.data <- subset(coding.data, coding.data$`Was this audio codable?`=="Yes")

video.Friendly <-
  data.frame(
    coding.data$Coder.Name..3.letter.initials.,
    coding.data$Dentist.Sample.ID..ex..102.1.,
    coding.data$Friendly
  )
names(video.Friendly) <- c("NetId", "Trial" , "Friendly")
md.Friendly <-
  melt(video.Friendly, id.vars = cbind("Trial", "NetId"))

cast.Friendly <- cast(md.Friendly, Trial ~ variable + NetId, sum)
cast.Friendly <- data.frame(cast.Friendly)
cast.Friendly <- na.omit(cast.Friendly)
rownames(cast.Friendly) <- cast.Friendly$Trial
# all.codings.factor <-merge(all.codings.factor, cast.Friendly, by.y = "Trial")
cast.Friendly$Trial <- as.factor(cast.Friendly$Trial)
cast.Friendly$Trial <- NULL
str(cast.Friendly)
DescTools::ICC(cast.Friendly)

video.Helpfulness <-
  data.frame(
    coding.data$Coder.Name..3.letter.initials.,
    coding.data$Dentist.Sample.ID..ex..102.1.,
    coding.data$Helpfulness
  )
names(video.Helpfulness) <- c("NetId", "Trial" , "Helpfulness")
md.Helpfulness <-
  melt(video.Helpfulness, id.vars = cbind("Trial", "NetId"))

cast.Helpfulness <-
  cast(md.Helpfulness, Trial ~ variable + NetId, sum)
cast.Helpfulness <- data.frame(cast.Helpfulness)
cast.Helpfulness <- na.omit(cast.Helpfulness)
rownames(cast.Helpfulness) <- cast.Helpfulness$Trial
# all.codings.factor <-merge(all.codings.factor, cast.Helpfulness, by.y = "Trial")
cast.Helpfulness$Trial <- NULL
str(cast.Helpfulness)
DescTools::ICC(cast.Helpfulness)

video.Negativity <-
  data.frame(
    coding.data$Coder.Name..3.letter.initials.,
    coding.data$Dentist.Sample.ID..ex..102.1.,
    coding.data$Negativity
  )
names(video.Negativity) <- c("NetId", "Trial" , "Negativity")
md.Negativity <-
  melt(video.Negativity, id.vars = cbind("Trial", "NetId"))

cast.Negativity <- cast(md.Negativity, Trial ~ variable + NetId, sum)
cast.Negativity <- data.frame(cast.Negativity)
cast.Negativity <- na.omit(cast.Negativity)
rownames(cast.Negativity) <- cast.Negativity$Trial
# all.codings.factor <- merge(all.codings.factor, cast.Negativity, by.y = "Trial")
cast.Negativity$Trial <- NULL
str(cast.Negativity)
DescTools::ICC(cast.Negativity)
x <- na.omit(data.frame(coding.data$Friendly, coding.data$Negativity, coding.data$Helpfulness))
cor(x)


# write.csv(all.codings.factor,"C:/Felix/Felix/Toothbrush Study/all.codings.factor.csv")

```

```{r coder and confederate comparisions}
coding.confederate.data <-
  read_excel("C:/Felix/Felix/Toothbrush Study/confederate and coder comparision.xlsx",
             na = c("", "n/a"))

t.test(coding.confederate.data$Friendliness~coding.confederate.data$Source,var.equal=FALSE)
t.test(coding.confederate.data$Curtness~coding.confederate.data$Source,var.equal=FALSE)
t.test(coding.confederate.data$Warmth~coding.confederate.data$Source,var.equal=FALSE)
t.test(coding.confederate.data$Rude~coding.confederate.data$Source,var.equal=FALSE)
t.test(coding.confederate.data$Length~coding.confederate.data$Source,var.equal=FALSE)
```